export default [
  {
    shortName: 'fm4',
    name: 'radio FM4',
    streamurl: 'http://mp3stream1.apasf.apa.at:8000/;',
    tracklist: 'http://hop.orf.at/img-trackservice/fm4.js',
    curProgram: 'http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=Wochen-Plan-Fm4.xml',
    website: 'http://fm4.orf.at',
    color: '#FFDF00',
    dark: true,
  },
  {
    shortName: 'oe3',
    name: 'Hitradio Ö3',
    streamurl: 'http://mp3stream7.apasf.apa.at:8000/;',
    tracklist: 'http://oe3meta.orf.at/oe3mdata/WebPlayerFiles/PlayList400.json',
    curProgram: 'http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-oe3.xml',
    website: 'http://oe3.orf.at/',
    color: '#D80926',
    dark: false,
  },
  {
    shortName: 'oe1',
    name: 'Radio Österreich 1',
    streamurl: 'http://mp3stream3.apasf.apa.at:8000/;',
    tracklist: 'http://hop.orf.at/img-trackservice/oe1.js',
    curProgram: 'http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-oe1.xml',
    website: 'http://oe1.orf.at/',
    color: '#B70E0B',
    dark: false,
  },
  {
    shortName: 'bgl',
    name: 'Radio Burgenland',
    streamurl: 'http://194.232.200.146:8000/;',
    tracklist: 'http://hop.orf.at/img-trackservice/bgl.js',
    curProgram: 'http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-bgl.xml',
    website: 'http://burgenland.orf.at/radio/',
    color: '#F1BD15',
    dark: true,
  },
  {
    shortName: 'ktn',
    name: 'Radio Kärnten',
    streamurl: 'http://194.232.200.145:8000/;',
    website: 'http://kaernten.orf.at/radio/',
    color: '#D70010',
    dark: false,
  },
  {
    shortName: 'noe',
    name: 'Radio Niederösterreich',
    streamurl: 'http://mp3stream8.apasf.apa.at:8000/;',
    tracklist: 'http://hop.orf.at/img-trackservice/noe.js',
    curProgram: 'http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-noe.xml',
    website: 'http://noe.orf.at/radio/',
    color: '#F1BD15',
    dark: true,
  },
  {
    shortName: 'ooe',
    name: 'Radio Oberösterreich',
    streamurl: 'http://194.232.200.148:8000/;',
    tracklist: 'http://hop.orf.at/img-trackservice/ooe.js',
    curProgram: 'http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-ooe.xml',
    website: 'http://ooe.orf.at/radio/',
    color: '#D70010',
    dark: false,
  },
  {
    shortName: 'sbg',
    name: 'Radio Salzburg',
    streamurl: 'http://194.232.200.147:8000/;',
    tracklist: 'http://hop.orf.at/img-trackservice/sbg.js',
    curProgram: 'http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-sbg.xml',
    website: 'http://salzburg.orf.at/radio/',
    color: '#D70010',
    dark: false,
  },
  {
    shortName: 'stm',
    name: 'Radio Steiermark',
    streamurl: 'http://mp3stream9.apasf.apa.at:8000/;',
    tracklist: 'http://hop.orf.at/img-trackservice/stmk.js',
    curProgram: 'http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-stm.xml',
    website: 'http://steiermark.orf.at/radio/',
    color: '#0A7A4A',
    dark: false,
  },
  {
    shortName: 'tir',
    name: 'Radio Tirol',
    streamurl: 'http://194.232.200.159:8000/;',
    tracklist: 'http://hop.orf.at/img-trackservice/tir.js',
    curProgram: 'http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-tir.xml',
    website: 'http://tirol.orf.at/radio/',
    color: '#D70010',
    dark: false,
  },
  {
    shortName: 'vbg',
    name: 'Radio Vorarlberg',
    streamurl: 'http://194.232.200.149:8000/;',
    tracklist: 'http://hop.orf.at/img-trackservice/vbg.js',
    curProgram: 'http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-vbg.xml',
    website: 'http://vorarlberg.orf.at/radio/',
    color: '#D70010',
    dark: false,
  },
  {
    shortName: 'wie',
    name: 'Radio Wien',
    streamurl: 'http://mp3stream17.apasf.apa.at:8000/;',
    tracklist: 'http://hop.orf.at/img-trackservice/wien.js',
    curProgram: 'http://tube.orf.at/broadcastSchedule/currentBroadcast.jsonp?scheme=sendungsplan-wie.xml',
    website: 'http://wien.orf.at/radio/',
    color: '#CF5611',
    dark: false,
  },
];
